<?php

/**
 * Implements hook_form_alter()
 *
 * Hide the title field. (It will be assigned a value on form submission.)
 */
function tracking_data_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'tracking_data_node_form') {
    $form['title']['#type'] = 'hidden';

    // Title field must have something in it to submit, but it will
    // be changed after submission.
    $form['title']['#value'] = 'title';
    $form['#submit'][] = '_tracking_data_form_submit';
  }
}

/**
 * Called on form submission. Set the title to a generated value.
 */
function _tracking_data_form_submit($form, &$form_state) {
  global $user;
  $username = $user->name;

  $date = $form_state['values']['field_data_date'][0]['value'];
  $date_string = strftime('%d %b %Y', $date);

  $form_state['values']['title'] = $username . ": data for " . $date_string;
}
